### PR TITLE
Convert to use rosbags

### PR DESCRIPTION
**Pull request by amarburg**
Update script to use [rosbags](https://gitlab.com/ternaris/rosbags) and [rosbags-image](https://gitlab.com/ternaris/rosbags-image) to run anywhere, even without a working ROS installation.

Also be open-minded to code cleanup or refactoring to make it more maintainable.

### CODE REVIEW

**Comment by amarburg** [comment]
Also, feel free to ignore or discard the code I've already checked into the branch.  This was a rushed initial cut which I never got working.

**Comment by amarburg** [comment]
Update `setup.py` and remove `package.xml` and `manifest.xml`.  

- should install prerequisites (rosbag and rosbag-image)
- Also set up console-scripts  or entrypoints in setup.py

Should be able to `pip install .` the package and then use it.

On the first try, it's working, though!

**Comment by amarburg** [comment]
Ping @anand2718 ;  can you look at the issues above and we'll get this MR merged.

**Comment by anand2718** [comment]
Works with pip install now - I haven't converted bag2images.py yet, should I get that working with rosbags before merging?

**Comment by amarburg** [comment]
Would be nice.  How much effort will it be?

**Comment by anand2718** [comment]
I think we're almost good to merge - could you take a look and test it a bit before?

**Comment by amarburg** [comment]
I'll have a look when I have a chance ... thanks

**Comment by lauralindzey** [comment]
I've started testing this on the remus laptop (auv3), with an eye towards using it to give Craig a video extracted from the camera data:

~~~
git clone https://github.com/apl-ocean-engineering/bag2video
pip install -e .
pip install --upgrade pillow
bag2video mission271_cam_[...].bag /ngr/phoenix.image_raw
~~~

It seems to be doing the right thing, BUT it's taking forever. It only processes frames at ~5Hz to start (has now slowed to ~1Hz), and the resulting video is going to be huge (~30G for < 2 hours of camera data)

1. can you improve the documentation of the --scale parameter? I *think* that it might be an option to downsample images and wind up with a smaller mp4. If this is the case, would I use 0.5 or 2 to scale width/height to half of the pixels in the raw data?
2. could there be an option to only use every N-th frame?

**Comment by amarburg** [comment]
This doesn't address Laura's `bag2video` speed concern, but I think a major bottleneck for `bag2image` is _encoding_ the output files.  PNG compression is fairly slow. 

One way to accelerate this would be to parallelize the image writing (write N images at once)

**Comment by amarburg** [comment]
Running a brief head-to-head, I get:

`main`:
```
Wrote 78 messages to 106 frames in 45.07 seconds
```

This MR:
```
Wrote 71 messages to 89 frames in 25.64 seconds
```

There are some much bigger questions as to why they're writing different numbers of messages (the source rosbag has 89 `image_raw`s in it). ??!?   But the two solutions are ... in the same order of magnitude.

**Comment by amarburg** [comment]
This has been absorbed into #4

**Pull request closed without merging**
